# Assignment-4
## UCS420 "Cognitive Computing"
## NumPy - Introduction 1

In [1]:
import numpy as np


## Q.1 Create a NumPy 1D-array with 5 elements and perform basic operations

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
print("Original array:", arr1)


Original array: [1 2 3 4 5]


### a) Addition of 2 to all the elements

In [3]:
add_result = arr1 + 2
add_result


array([3, 4, 5, 6, 7])

### b) Multiply 3 with all the elements

In [4]:
mul_result = arr1 * 3
mul_result


array([ 3,  6,  9, 12, 15])

### c) Divide every element by 2

In [5]:
div_result = arr1 / 2
div_result


array([0.5, 1. , 1.5, 2. , 2.5])

## Q.2 Questions on Basic NumPy Array

### a) Reverse the NumPy array

In [6]:
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
reversed_arr


array([5, 4, 6, 3, 2, 1])

### b) Find the most frequent value and its indices
**i.** `x = np.array([1,2,3,4,5,1,2,1,1,1])`

In [7]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)
most_frequent_x = values[np.argmax(counts)]
indices_x = np.where(x == most_frequent_x)[0]

print("Most frequent value:", most_frequent_x)
print("Indices:", indices_x)


Most frequent value: 1
Indices: [0 5 7 8 9]


**ii.** `y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])`

In [8]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values_y, counts_y = np.unique(y, return_counts=True)
most_frequent_y = values_y[np.argmax(counts_y)]
indices_y = np.where(y == most_frequent_y)[0]

print("Most frequent value:", most_frequent_y)
print("Indices:", indices_y)


Most frequent value: 1
Indices: [0 1 2]


## Q.3 2-D array — access elements using row and column indices
`arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])`

In [9]:
arr2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])
arr2d


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

### a) Access 1st row, 2nd column

In [10]:
arr2d[0, 1]


np.int64(20)

### b) Access 3rd row, 1st column

In [11]:
arr2d[2, 0]


np.int64(70)

## Q.4 1-D NumPy array with 25 evenly spaced numbers from 10 to 100
The array is named after the student (`ehsen`) as requested.

In [12]:
ehsen = np.linspace(10, 100, 25)
ehsen


array([ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
        40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
        70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
       100.  ])

In [13]:
print("Dimensions (ndim):", ehsen.ndim)
print("Shape:", ehsen.shape)
print("Total elements (size):", ehsen.size)
print("Data type:", ehsen.dtype)
print("Total bytes consumed (nbytes):", ehsen.nbytes)


Dimensions (ndim): 1
Shape: (25,)
Total elements (size): 25
Data type: float64
Total bytes consumed (nbytes): 200


### Transpose using `reshape()`
A 1-D array has only one axis, so there is nothing to swap — reshaping it to a column vector `(25, 1)` is the practical equivalent of "transposing" it into a 2-D column form.

In [14]:
ehsen_transposed_reshape = ehsen.reshape(25, 1)
ehsen_transposed_reshape


array([[ 10.  ],
       [ 13.75],
       [ 17.5 ],
       [ 21.25],
       [ 25.  ],
       [ 28.75],
       [ 32.5 ],
       [ 36.25],
       [ 40.  ],
       [ 43.75],
       [ 47.5 ],
       [ 51.25],
       [ 55.  ],
       [ 58.75],
       [ 62.5 ],
       [ 66.25],
       [ 70.  ],
       [ 73.75],
       [ 77.5 ],
       [ 81.25],
       [ 85.  ],
       [ 88.75],
       [ 92.5 ],
       [ 96.25],
       [100.  ]])

### Can we do the same with the `.T` attribute?
Directly calling `.T` on the original 1-D array does **not** change anything — NumPy treats a 1-D array as its own transpose, so its shape stays `(25,)`. `.T` only swaps axes when there is more than one axis. If we first reshape it into 2-D (e.g. `(1, 25)`), then `.T` behaves like a true transpose and gives the same `(25, 1)` result as above.

In [15]:
print("ehsen.T shape (no change on 1-D array):", ehsen.T.shape)

ehsen_2d = ehsen.reshape(1, 25)
ehsen_2d_T = ehsen_2d.T
print("Reshaped to (1,25) then .T shape:", ehsen_2d_T.shape)

print("Same result as reshape(25,1)?", np.array_equal(ehsen_2d_T, ehsen_transposed_reshape))


ehsen.T shape (no change on 1-D array): (25,)
Reshaped to (1,25) then .T shape: (25, 1)
Same result as reshape(25,1)? True


## Q.5 2-D Array of three rows and four columns (`ucs420_ehsen`)

In [16]:
ucs420_ehsen = np.array([[10, 20, 30, 40],
                          [50, 60, 70, 80],
                          [90, 15, 20, 35]])
ucs420_ehsen


array([[10, 20, 30, 40],
       [50, 60, 70, 80],
       [90, 15, 20, 35]])

### Compute mean, median, max, min, unique elements

In [17]:
print("Mean:", ucs420_ehsen.mean())
print("Median:", np.median(ucs420_ehsen))
print("Max:", ucs420_ehsen.max())
print("Min:", ucs420_ehsen.min())
print("Unique elements:", np.unique(ucs420_ehsen))


Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]


### Reshape the array to four rows and three columns (`reshaped_ucs420_ehsen`)

In [18]:
reshaped_ucs420_ehsen = ucs420_ehsen.reshape(4, 3)
reshaped_ucs420_ehsen


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [15, 20, 35]])

### Resize the array to two rows and three columns (`resized_ucs420_ehsen`)
`np.resize` fills the new shape from the flattened original array (repeating/truncating as needed) instead of requiring the same total number of elements as `reshape` does.

In [19]:
resized_ucs420_ehsen = np.resize(ucs420_ehsen, (2, 3))
resized_ucs420_ehsen


array([[10, 20, 30],
       [40, 50, 60]])