# Assignment 5
## UCS420 "Cognitive Computing"
## NumPy - II

In [1]:
import numpy as np


## Q.1 Sensor readings (temperature)

In [2]:
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
temperature


array([25, 28, 31, 35, 38, 27, 33, 40])

### a) Add 2°C to every reading using vectorization

In [3]:
corrected_temperature = temperature + 2
corrected_temperature


array([27, 30, 33, 37, 40, 29, 35, 42])

### b) Convert all temperatures from Celsius to Fahrenheit ($F = \frac{9}{5}C + 32$)

In [4]:
fahrenheit = (9/5) * temperature + 32
fahrenheit


array([ 77. ,  82.4,  87.8,  95. , 100.4,  80.6,  91.4, 104. ])

### c) Identify all readings greater than 32°C using Boolean indexing

In [5]:
above_32 = temperature[temperature > 32]
above_32


array([35, 38, 33, 40])

### d) Count how many readings exceed 32°C

In [6]:
count_above_32 = np.sum(temperature > 32)
count_above_32


np.int64(4)

### e) Why vectorization and Boolean indexing are more efficient than an explicit loop
NumPy arrays store elements in contiguous blocks of memory as a fixed data type. Vectorized operations (like `temperature + 2`) are implemented in optimized, pre-compiled C code that operates on the whole array at once — there's no per-element Python bytecode interpretation, no repeated type-checking, and the CPU can use techniques like SIMD (processing several values per instruction) and better cache usage. A Python `for` loop, by contrast, re-enters the interpreter for every single element, which carries a lot of overhead.\n\nBoolean indexing works the same way: `temperature > 32` computes a single Boolean mask over the entire array in one vectorized pass, and then that mask is used to select matching elements in another vectorized pass — again avoiding an explicit Python-level loop with `if` checks. For large datasets this difference in speed becomes dramatic, and the code is also shorter and easier to read.

## Q.2 Daily steps recorded by four users over three days

In [7]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])
steps


array([[5000, 6200, 7100],
       [8000, 7500, 9000],
       [4500, 5100, 4800],
       [9000, 8500, 9500]])

### a) Total steps recorded

In [8]:
total_steps = steps.sum()
total_steps


np.int64(84200)

### b) Mean number of steps

In [9]:
mean_steps = steps.mean()
mean_steps


np.float64(7016.666666666667)

### c) Maximum and minimum values

In [10]:
max_steps = steps.max()
min_steps = steps.min()
print("Max:", max_steps)
print("Min:", min_steps)


Max: 9500
Min: 4500


### d) Total steps for each day (axis=0)

In [11]:
steps_per_day = steps.sum(axis=0)
steps_per_day


array([26500, 27300, 30400])

### e) Total steps for each user (axis=1)

In [12]:
steps_per_user = steps.sum(axis=1)
steps_per_user


array([18300, 24500, 14400, 27000])

### f) User/day position containing the maximum number of steps (argmax)

In [13]:
flat_index = steps.argmax()
user_idx, day_idx = np.unravel_index(flat_index, steps.shape)

print(f"Maximum value {steps[user_idx, day_idx]} is at User {user_idx + 1}, Day {day_idx + 1}")
print("(0-based) row index:", user_idx, "| column index:", day_idx)


Maximum value 9500 is at User 4, Day 3
(0-based) row index: 3 | column index: 2


## Q.3 Slicing, views vs. copies, reshape, flatten/ravel

### a) Create the original array

In [14]:
original = np.array([1, 2, 3, 4, 5, 6])
original


array([1, 2, 3, 4, 5, 6])

### b) Create a slice (index 1 to 4) named `subset`

In [15]:
subset = original[1:5]
subset


array([2, 3, 4, 5])

### c) Modify the first element of `subset` to 999 and display both

In [16]:
subset[0] = 999
print("original:", original)
print("subset:", subset)


original: [  1 999   3   4   5   6]
subset: [999   3   4   5]


A basic slice (`original[1:5]`) is a **view**, not a copy — it shares the same underlying memory buffer as `original`. Changing `subset[0]` therefore also changes `original[1]`, which is visible above.

### d) Create another slice using `.copy()`, modify it, and display both

In [17]:
original_copy_slice = original[1:5].copy()
original_copy_slice[0] = 500

print("original:", original)
print("copied slice:", original_copy_slice)


original: [  1 999   3   4   5   6]
copied slice: [500   3   4   5]


Because `.copy()` allocates a brand-new array with its own memory, modifying `original_copy_slice` has **no effect** on `original` this time.

### e) Create an array 1–12 with `np.arange()` and reshape into a 3×4 matrix

In [18]:
matrix = np.arange(1, 13).reshape(3, 4)
matrix


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### f) Extract from the 3×4 matrix

In [19]:
first_row = matrix[0, :]
first_row


array([1, 2, 3, 4])

In [20]:
last_row = matrix[-1, :]
last_row


array([ 9, 10, 11, 12])

In [21]:
second_column = matrix[:, 1]
second_column


array([ 2,  6, 10])

In [22]:
# Rows 1-2 (0-based indices 1 and 2) and columns 2-3 (0-based indices 2 and 3)
sub_block = matrix[1:3, 2:4]
sub_block


array([[ 7,  8],
       [11, 12]])

### g) Flattened versions using `flatten()` and `ravel()`

In [23]:
flattened = matrix.flatten()
raveled = matrix.ravel()

print("flatten():", flattened)
print("ravel():", raveled)


flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]


### h) Modify an element returned by `ravel()` — does it affect the original?

In [24]:
raveled[0] = -1
print("raveled:", raveled)
print("original matrix:\n", matrix)


raveled: [-1  2  3  4  5  6  7  8  9 10 11 12]
original matrix:
 [[-1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


`ravel()` returns a **view** whenever possible (the matrix here is contiguous), so modifying `raveled[0]` also changes `matrix[0, 0]` — the original array **is** affected.

### i) Modify an element returned by `flatten()` — does it affect the original?

In [25]:
flattened[1] = -2
print("flattened:", flattened)
print("original matrix:\n", matrix)


flattened: [ 1 -2  3  4  5  6  7  8  9 10 11 12]
original matrix:
 [[-1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


`flatten()` always returns a **copy**, so modifying `flattened[1]` leaves `matrix` completely unchanged.

### j) Shape, ndim, size, and dtype of the original 3×4 matrix

In [26]:
print("Shape:", matrix.shape)
print("ndim:", matrix.ndim)
print("Size:", matrix.size)
print("dtype:", matrix.dtype)


Shape: (3, 4)
ndim: 2
Size: 12
dtype: int64


## Q.4 Predicting a user's assistance score (Ordinary Least Squares)

In [27]:
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])
y = np.array([40, 65, 30, 85])


### a) Shape and dimensions of X

In [28]:
print("Shape of X:", X.shape)
print("Dimensions (ndim) of X:", X.ndim)


Shape of X: (4, 3)
Dimensions (ndim) of X: 2


### b) X.T and what the transpose represents

In [29]:
X_T = X.T
X_T


array([[ 6,  5,  8,  4],
       [70, 50, 80, 30],
       [ 3,  6,  2,  8]])

`X` has one row per user and one column per feature (sleep hours, activity level, stress level). `X.T` flips this layout so that it has one row per **feature** and one column per **user** — i.e. rows and columns are swapped. It's the same data, just reorganized so that each row now represents "all users' values for a single feature", which is exactly the shape needed for the matrix operations in the OLS formula below.

### c) Matrix product X.T @ X

In [30]:
XtX = X.T @ X
XtX


array([[  141,  1430,    96],
       [ 1430, 14700,   910],
       [   96,   910,   113]])

### d) Matrix inverse using np.linalg.inv()

In [31]:
XtX_inv = np.linalg.inv(XtX)
XtX_inv


array([[ 1.10521428, -0.09848746, -0.14581398],
       [-0.09848746,  0.00891203,  0.01190129],
       [-0.14581398,  0.01190129,  0.0368847 ]])

### e) Implement the Ordinary Least Squares equation $\beta = (X^TX)^{-1}X^Ty$

In [32]:
beta = XtX_inv @ X.T @ y
beta


array([-0.15921454,  0.14083853, 10.06302242])

### f) What do the resulting coefficients represent?

Each value in `beta` is the estimated weight for one of the three features (sleep hours, activity level, stress level) in a linear model:\n\n$$\text{assistance score} = \beta_1 \cdot \text{sleep} + \beta_2 \cdot \text{activity} + \beta_3 \cdot \text{stress}$$\n\nConcretely, `beta[0]` is how much the predicted assistance score changes for each extra hour of sleep (holding the other two features fixed), `beta[1]` is the change per unit increase in activity level, and `beta[2]` is the change per unit increase in stress level — with the sign indicating whether that feature pushes the score up or down.

### g) Predicted assistance score for a new user

In [33]:
new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta
predicted_score


np.float64(75.27862544779134)